version: "3.8"

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - "portainer_data:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8000:8000
      - 9000:9000

volumes:
    portainer_data:
