version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123321
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8000:8080